PROXY_TYPE_SOCKS4 = SOCKS4 = 1
PROXY_TYPE_SOCKS5 = SOCKS5 = 2
PROXY_TYPE_HTTP = HTTP = 3
HOME_TIMELINE_TYPE_FOR_YOU = "HomeTimeline"
HOME_TIMELINE_TYPE_FOLLOWING = "HomeLatestTimeline"
INBOX_PAGE_TYPE_TRUSTED = "trusted"
INBOX_PAGE_TYPE_UNTRUSTED = "untrusted"
INBOX_PAGE_TYPES = (INBOX_PAGE_TYPE_TRUSTED, INBOX_PAGE_TYPE_UNTRUSTED)
MEDIA_TYPE_VIDEO = "video"
MEDIA_TYPE_GIF = "animated_gif"
MEDIA_TYPE_IMAGE = MEDIA_TYPE_PHOTO = "photo"